const SEND_API_REQUEST = "SEND_API_REQUEST";
const FETCH_RECIPE_INSTRUCTION = "FETCH_RECIPE_INSTRUCTION";
const SET_RECIPE_ITEM = "SET_RECIPE_ITEM";
const SET_RECIPE_DATA = "SET_RECIPE_DATA";
const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
const SET_SEARCH_ITEM = "SET_SEARCH_ITEM";
const CLEAR_RECIPE_DATA = "CLEAR_RECIPE_DATA";
export {
  SEND_API_REQUEST,
  SET_RECIPE_DATA,
  ADD_TO_FAVOURITE,
  REMOVE_FROM_FAVOURITE,
  FETCH_RECIPE_INSTRUCTION,
  SET_RECIPE_ITEM,
  SET_SEARCH_ITEM,
  CLEAR_RECIPE_DATA,
};
